POST http://localhost:3000/tenants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJyZzFaWGZiQTRvbTNtbmVzb2c5U0F5VzZtSmlwVmVBcGZWdWhmd090TUFBIn0.eyJleHAiOjE2NzY1NTY3MDEsImlhdCI6MTY3NjU1NjY0MSwianRpIjoiOWIzMDc2YWEtODEzMy00YzVjLTg1YzUtZWIwZDcyYmJiNTEyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoyODA4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNDMxODE4NGEtODJlMC00MzE5LWFmMzktMTYxZWNlNTY2NmI5IiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6IjhhOTg0MzdkLTNmYTktNGYwYi05MTRkLWI4MWJjZmU1NDljOCIsImFjciI6IjEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI4YTk4NDM3ZC0zZmE5LTRmMGItOTE0ZC1iODFiY2ZlNTQ5YzgiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.WrPW7kov0nkLtgS-d9WLlL-CPmKK2j1Tx57H7BuPBuWBlIFRq3jNceBXd4op9OT3xWE4b_EGIkOFRc-IIRPRSHmBJODJ0E6aXndKPEfHXhjEtpE0mtD26a-eWp8lNz0yfsmvobE8rZl1Mo0tsmHoEHl346zc7d8Bb0slT4WTFWi4Lnr8sDDSHzxNgpJ_4MHxkuhOOorN6i_Uu1UjUSlnIAmAZNE_gEkD-nMJisMXIzP7lKYZ5BaRsnOSNbEi6xigb6NCboZSNMo1a5C2bl6qG8Hl2ilMhLO0mdCSufX8lHEmttrOn7kDFrhji0RykeSEH4JlX6ddGSbT9i6Wqylc4w

{
  "subdomain": "certi",
  "name": "CERTI"
}
