POST http://localhost:3000/tenants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJNY0U1bndCcmZ1OWtHT0FVNkY4ZERsYU10MEJMeTMzam5Sc05NRmFGUTFjIn0.eyJleHAiOjE2NzYzODU2MzMsImlhdCI6MTY3NjM4NTU3MywianRpIjoiN2U5MDdkNDctMmI2NC00ZTc5LThlYjAtODEwZjM3MTA2MTk3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoyODA4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTQ1YWM5MWEtN2Q0Yi00N2I3LWIxMzUtNDQyOTFiMjkxNjExIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6IjdjMWQ3MmNjLTA2YWUtNGY3Yy1iNTc5LTUwMDg5MjFmNTFmYyIsImFjciI6IjEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI3YzFkNzJjYy0wNmFlLTRmN2MtYjU3OS01MDA4OTIxZjUxZmMiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.LH-WrRb5Jcsokciib6casfrgdLfxlFciHNdTuw2-tSTJwDrz_NQis5RRyG1hPiv--njapgLQsh_-5o_uASLtgDG8Yi5mCSCvJa-r2bsieZMeu-bIrC3-XIDgk6HpCFu1sKiYhh9iBvv-vWpo3VwJDtoIJyMiIszcplVEcQLOZVrcYJ6wE_e9bPOGFymDjnISSE_ZVnduNBAFfeaNpUo9SLjaZLDcC1LSDezjk8K3isG9w3BmBk_ELgEDJGVgKLaj3h-__NP6nh8qh7ikJy49Tz5HgehHy7_u9rOYx6Hsh_AfLVdT0FTwnr7Y51orfUWZoiPFZvRTRcxDRdBkHSMdqA

{
  "subdomain": "rea",
  "name": "REA"
}
