POST http://localhost:3000/tenants HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJNY0U1bndCcmZ1OWtHT0FVNkY4ZERsYU10MEJMeTMzam5Sc05NRmFGUTFjIn0.eyJleHAiOjE2NzYzMjA2MDMsImlhdCI6MTY3NjMyMDU0MywianRpIjoiNjdkYjkyZWUtY2JlYS00YzQxLWJjOGItZTdiZjNkOGZhMjFlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoyODA4MC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTQ1YWM5MWEtN2Q0Yi00N2I3LWIxMzUtNDQyOTFiMjkxNjExIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6Ijc2ZTJiOGE0LTljM2QtNDkxYy05NzcxLWUyNDNmYzM2MmQ2MCIsImFjciI6IjEiLCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiI3NmUyYjhhNC05YzNkLTQ5MWMtOTc3MS1lMjQzZmMzNjJkNjAiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.EHJNcWf3r5tRNfy4FUnSjNBSne3FWxufMioUuUEAE67t5Lv4YyIDYvIXubdDzC41ube1hRKdkyqpTzyDJCNef4LP3br3_xyh4AMwUa4OWq85Q6dlVWrfmUNLFqjfSMYKeYdpsswGohFUqGs2W75q7uLx1WgkuLyGWWlpJxIEkkG8-wTFRx8FzgHewcvxH3DfAPDMK0pHgiq2AnXMvpRuaRWYQ4x1kblSXA1XFoQmn-YUqE_PaaErx4QYP2PIccY9emvcuOpP-nzeGOHNf9gVMnKEmi9gVhEKJl99YzW5t5rbUFjYA8Gk4su9q0Wl-35uyCxIzpSpChFlq5UNy0C92g

{
  "subdomain": "lab",
  "name": "LAB"
}
